### ISSUE TITLE
issues about UTM coordinate

### ISSUE THREAD

**Issue by riyueshi** [ethz-asl/aerial_mapper#15]
Hi, @hitimo 
  I read the source code and got some question about produce of orthophoto as following:

1. if I got the GPS geodesic coordinate of the images, the geodesic coordinate is not a Cartesian coordinate, when I prefer the coordinate transfer should I use UTM projection to project the GPS coordinate to an Cartesian coordinate? if not, how to handle the earth curve error?

2. I noticed that during the process of orthophoto generate the landmark coordinate is projected through UTM ( the variable landmark_UTM in "ortho-backward-grid.cc" seems mean that ), how does those UTM coordinate computed, does simply add an constant step in X and Y direction work for that?

3. I am not familiar with the coordinate transfer between geodesic coordinate and Cartesian coordinate (I have already google that but still not so clear ), In the produce of orthophoto, In which step should I perform the UTM projection?

Many Thanks,
Miller

**Comment by laxnpander** [comment]
Hey @riyueshi ,

I am not the author but maybe I can help a little:

1) Yes definitely, I would recommend using UTM32 instead of WGS84, it makes everything so much easier and more intuitive. Especially as GridMap assumes an aspect ratio of 1:1. You might also be able to do it with WGS84, but it will currently not be worth it. The accuracy loss through conversion is negligible compared to the rest of the uncertainties.

2) If I remember that function right, it iterates through the grid cells and extracts a world position from GridMap. So jeah, you could also add up a constant iteratevly to let's say your topleft corner in X and Y corresponding to the size of your image. Only make sure your coordinate frames align (y+ is Northing, x+ is Easting).

3) You will need a pose ([R|t]) of your camera. That's where utm coordinates should be as x -> Eastings, y -> Northings. Everything else will fall into place afterwards. 

Best regards,
Alex

**Comment by riyueshi** [comment]
Hi @laxnpander ,
  Thanks for your reply. But I think this is not the solution for a large scale orthophoto generate. The error caused by earth curvature seem can not be neglect (as shown in this [web](http://earthcurvature.com/), a 5 km geodetics line may cause about 2 meter height difference  ). And use UTM projection transfer the WGS84 can not handle this error.I did some work those days, and got some solution for those question. I think transfer the WGS84 coordinate to an cartesian coordinates in 3d space can be more accurate (something like ECEF or an local coordinate frame). In the case considering all those error If the XY coordinate is determine by UTM coordinate, to get the Z coordinate of this landmark acquire us to project back to the earth surface. And to acquire the XY coordinate of landmark by add up a constant and then just get the Z coordinate from the corresponding gridmap is actually an orthographic projection not UTM projection (if the landmark_UTM is acquired in this way the name of this variable is sometimes confused). As you said, all those error course by projection and earth curvature is negligible for a small scene. 

Best regards,
Miller
